# Generated by Django 6.0.3 on 2026-03-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingsession',
            name='preferred_time',
            field=models.CharField(default='10:00 AM', max_length=20),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
